# Generated by Django 3.2.16 on 2022-10-23 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_user_user_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='出勤時間')),
                ('end_time', models.TimeField(verbose_name='退勤時間')),
                ('break_time', models.TimeField(verbose_name='休憩時間')),
                ('comment', models.TextField(verbose_name='業務内容')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='社員ID')),
            ],
        ),
    ]
