# Generated by Django 3.2.16 on 2022-10-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_alter_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='break_time',
            field=models.TimeField(blank=True, default='01:00:00', null=True, verbose_name='休憩時間'),
        ),
    ]
