# Generated by Django 3.2.16 on 2022-10-28 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_alter_user_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.TimeField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='「00:00」の形式で入力してください。', regex='^([01]?[0-9]|2[0-3]):([0-5][0-9])$')], verbose_name='出勤時間'),
        ),
    ]
