# Generated by Django 3.2.16 on 2022-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_alter_work_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='出勤時間'),
        ),
    ]
